services:
  mysql:
    image: mysql:8.4.0
    container_name: tendance-mysql
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7.2.5
    container_name: tendance-redis
    env_file:
      - .env
    environment:
      REDIS_DATABASES: 16
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:latest
    container_name: tendance-mongodb
    env_file:
      - .env
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}

#  neo4j:
#    image: neo4j:5.20-community
#    container_name: tendance-neo4j
#    environment:
#      NEO4J_AUTH: neo4j/${NEO4J_AUTH}
#    ports:
#      - "7473:7474"
#      - "7685:7687"
#    volumes:
#      - neo4j_data:/data

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
#    container_name: tendance-elasticsearch
#    environment:
#      - discovery.type=single-node
#    ports:
#      - "9209:9200"
#      - "9309:9300"
#    volumes:
#      - es_data:/usr/share/elasticsearch/data

volumes:
  mysql_data:
#  postgres_data:
  redis_data:
#  neo4j_data:
  mongodb_data:
#  es_data:
